apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: etcxytcys-python 
  janus-idp.io/tekton: etcxytcys-python
  backstage.io/kubernetes-id: etcxytcys-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: etcxytcys-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml